config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#        root GET    /                           home#index
#       about GET    /about(.:format)            home#about
#     contact GET    /contact(.:format)          home#contact
#   edit_user GET    /users/edit(.:format)       users#edit
#       users GET    /users(.:format)            users#index
#             POST   /users(.:format)            users#create
#    new_user GET    /users/new(.:format)        users#new
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
#        kids GET    /kids(.:format)             kids#index
#             POST   /kids(.:format)             kids#create
#     new_kid GET    /kids/new(.:format)         kids#new
#    edit_kid GET    /kids/:id/edit(.:format)    kids#edit
#         kid GET    /kids/:id(.:format)         kids#show
#             PATCH  /kids/:id(.:format)         kids#update
#             PUT    /kids/:id(.:format)         kids#update
#             DELETE /kids/:id(.:format)         kids#destroy
#     schools GET    /schools(.:format)          schools#index
#             POST   /schools(.:format)          schools#create
#  new_school GET    /schools/new(.:format)      schools#new
# edit_school GET    /schools/:id/edit(.:format) schools#edit
#      school GET    /schools/:id(.:format)      schools#show
#             PATCH  /schools/:id(.: format)      schools#update
#             PUT    /schools/:id(.:format)      schools#update
#             DELETE /schools/:id(.:format)      schools#destroy
#       trips GET    /trips(.:format)            trips#index
#             POST   /trips(.:format)            trips#create
#    new_trip GET    /trips/new(.:format)        trips#new
#   edit_trip GET    /trips/:id/edit(.:format)   trips#edit
#        trip GET    /trips/:id(.:format)        trips#show
#             PATCH  /trips/:id(.:format)        trips#update
#             PUT    /trips/:id(.:format)        trips#update
#             DELETE /trips/:id(.:format)        trips#destroy
#       login GET    /login(.:format)            session#new
#             POST   /login(.:format)            session#create
#             DELETE /login(.:format)            session#destroy
#

Rails.application.routes.draw do
  get 'messages/messages'

  get 'messages/index'

    root :to => 'home#index'
    get '/about' => 'home#about'
    get '/contact' => 'home#contact'

    get '/users/edit' => 'users#edit', :as => :edit_user
    resources :users, :except => [:edit]

    resources :kids, :schools
    resources :trips do
  	 resources :comments

     post 'book' => 'trips#book'  	
     delete 'unbook/:kid_id' => 'trips#unbook', :as => :unbook
    end


    get '/login' => 'session#new'
    post 'login' => 'session#create'
    delete 'login' => 'session#destroy'

end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id                 :integer          not null, primary key
#  seats_available    :integer
#  user_id            :integer
#  school_id          :integer
#  direction          :string(255)
#  desired_start_time :time
#  date               :date
#  created_at         :datetime
#  updated_at         :datetime
#

class Trip < ActiveRecord::Base
	has_and_belongs_to_many :kids
	belongs_to :school
	belongs_to :user
	has_many :comments

	def seats_remaining
		return self.seats_available - self.kids.length
	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  # before_action :check_login
  
  def new
    @trip = Trip.new
  end

  def create    
    trip = Trip.new trip_params
    trip.user_id = @current_user.id
    trip.save   
    redirect_to trip 
  end

  def index
    # Current user's school list 
    @school_list = []
    @current_user.kids.each do |kid|
      @school_list << kid.school.id
    end

    # Trips that go to your school
    @trips = []
    @school_list.each do |school|
      Trip.all.each do |trip|
        if trip.school_id == school
          @trips << trip
        end
      end
    end

  end
  
  def show
    @trip = Trip.find params[:id]
  end

  def edit
    @trip = Trip.find params[:id]
  end

  def update
    trip = Trip.find params[:id]
    trip.update trip_params
    redirect_to trip
  end 

  def destroy
    trip = Trip.find params[:id]
    trip.delete
    redirect_to '/trips'
  end

  def book
    trip = Trip.find params[:trip_id]
    kid = Kid.find params[:kid_id]
    trip.kids << kid
    trip.save
    redirect_to trip
  end

  def unbook
    kid = Kid.find params[:kid_id]      # Find kid in the trip.kids array
    trip = Trip.find params[:trip_id]
    trip.kids.delete(kid)
    redirect_to trip
  end

  private
  def trip_params
    params.require(:trip).permit(:seats_available, :direction, :user_id, :school_id, :desired_start_time, :date, :comments => [])
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<div class="form_page">
	<div class="input-group">

	<%= form_for @trip do |f| %>
	<div class="form_segment">
		<%= f.label :seats_available  , "Seats Available" %>
		<select name="trip[seats_available]" , class="form-control", required>
		  <option value="1">1</option>
		  <option value="2">2</option>
		  <option value="3">3</option>
		  <option value="4">4</option>

		</select>
	</div>
	<div class="form_segment">
		<%= f.label :school, "School"  %>
		<select name="trip[school_id]", class="form-control", prompt="Select school", required>
			<option disabled>Select school</option>
			<% @current_user.schools.all.each do |school| %>
				<option value=<%= school.id %> > <%= school.name  %> </option>
			<% end %>
		</select>  
	</div>
	<div class="form_segment">
		<%= f.label :direction  , "Direction" %>
		<select name="trip[direction]" required , class="form-control" >
			<option disabled>Select direction</option>
			<option value="dropoff">Drop-off at school</option>
			<option value="pickup">Pick-up from school</option>
		</select>
	</div>

	<div class="form_segment">
		<%= f.label :desired_start_time  , "Start Time" %>
		<%= f.time_field :desired_start_time, required: true, :class => "form-control"  %>
	</div>
	<div class="form_segment">
		<%= f.label :date  , "Date" %>
		<%= f.date_field :date, required: true, :class => "form-control"  %>
	</div>

		<label></label>
		<%= f.submit %>
	<% end %>
</div>
</div>

app/views/trips/edit.html.erb
<div class="container">
<% if @current_user %>

	<h1>Edit your trip</h1>

	<%= render :partial => 'form' %> 
<% end %>
</div>

app/views/trips/index.html.erb
<div class="container">
	<h1>Carpooling rides avaliable in your area</h1>
	<div class="btn btn-group-lg btn-success btn-index"> 
		<%= link_to("New Ride", new_trip_path) %></div>


	<% @trips.each do |trip| %> 
	<% if trip.date >= Date.today %>
			<div class="index">
			
			<h4><strong>School: </strong> <%= link_to(trip.school.name, school_path(trip.school))  %> </h4>
			<h4><strong>Direction: </strong> <%= trip.direction.capitalize  %></h4>
			<h4><strong>Seats Remaining: </strong> <%= trip.seats_remaining %> </h4>
			<h4><strong>Date: </strong> <%= trip.date.strftime "%a, %B %d, %Y"  %></h4>
			<h4><strong>Time: </strong> <%= trip.desired_start_time.strftime "%l:%M %p" %></h4>
			</div>
			
			<div class="index">
			<h4><strong>Driver:</strong> <%= link_to(trip.user.first_name.capitalize, user_path(trip.user))  %></h4>
			<h4><strong>Suburb: </strong> <%= trip.user.suburb  %>, <%= trip.user.postcode  %> </h4>
			<h4><strong>Vehicle: </strong> <%= trip.user.car_brand  %> <%= trip.user.car_model  %></h4>
			<div class="btn btn-group-lg btn-warning" > <h4> <%= link_to "Further trip details ... ", trip_path(trip)  %> </h4> </div>

			</div>

			<div class="index">
	    <% if trip.direction == 'dropoff' #Dropoff at school %>
		    <% origin = trip.user.map_address %>
		    <% destination = trip.school.map_address %>
	    <% else %>
	    	 <% destination = trip.user.map_address %>
		    <% origin = trip.school.map_address %>
	    <% end %>

		<iframe
			   width="285" height="285" marginheight="0" marginwidth="0" frameborder="0" style="border:0"
		  src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyByeW3PQr7VCnExkxH9pas6C2EfAUDdDsQ&origin=<%= origin.gsub(' ', '+').gsub(',', '+').gsub('++', '+')  %>&destination=<%= destination.gsub(' ', '+').gsub(',', '+').gsub('++', '+')  %>&mode=driving ">
		</iframe>
			</div>
		<% end %>
		<% end %>

</div>

app/views/trips/new.html.erb
<div class="container">

	<h1>Write a new trip</h1>

	<%= render :partial => 'form' %> 
</div>

app/views/trips/show.html.erb
<div class="container">
<% if @current_user %>

	<div class="show_column">
		
		<h3><strong> <%= link_to(@trip.school.name, school_path(@trip.school))  %> </h3> </strong>
		<h4><strong>Direction: </strong> 
			<% if @trip.direction == "Dropoff" %>
				Drop-off at school
			<% else %>
				Pick-up from school
			<% end %>
			</h4>
		<h4> <strong>Time: </strong><%= @trip.desired_start_time.strftime "%l:%M %p"  %> </h4>
		<h4> <strong>Date: </strong><%= @trip.date.strftime "%a, %B %d, %Y"  %> </h4>
		<br>
		<h3> <strong> Seats Remaining:</strong> <%= @trip.seats_remaining  %> </h3> 
	<div class="request_seat">
	<h3>Request a seat</h3>
	<div>
 	<% if @current_user.kids && @trip.seats_remaining > 0 %>
		<%= form_tag trip_book_path(@trip) do   %> 
			<select name="kid_id", class="form-control">
				<option disabled>Select kid</option>
				<% @current_user.kids.each do |kid| %>
				  <option value="<%= kid.id %>"><%= kid.first_name.capitalize %></option>
				<% end %> 
			</select>
			<div> </div>
			<label></label>
			<%= submit_tag %>
		<% end %> 
	<% else %>
		<h4>Sorry. There are no available seats.</h4>
	<% end %>
	</div>
	</div>
	<br>

	</div>

	<div class="show_column">
		<h3> <strong> Driver: </strong><%= link_to @trip.user.first_name.capitalize, @trip.user  %></h3>
		<h4> <strong> Car: </strong> <%= @trip.user.car_brand  %> <%= @trip.user.car_model  %> </h4>
		<p>
      	<% if @trip.user.car_avatar.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag @trip.user.car_image %>
        <% else %>
             <%= image_tag @trip.user.car_avatar.url %> 
        <% end %>		
        </p>
		<% if @current_user.id == @trip.user_id || @current_user.admin %>
			<div class="btn btn-group-lg btn-warning" > <%= link_to('Edit Trip', edit_trip_path(@trip)) %> </div>
			<div class="btn btn-group-lg btn-danger" > <%= link_to 'Delete', @trip, :method => :delete, :data => { :confirm => "Are you sure?" }%> </div>
		<% end %>

	</div>

	<div class="show_column">
		<h2>Passengers</h2>
		<% @trip.kids.each do |kid| %>
		<div class="show_box">
			<div class="show_box_smaller">
		

      	<% if kid.avatar.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag kid.image %>
        <% else %>
             <%= image_tag kid.avatar.url %> 
        <% end %>


			</div>

			<div class="show_box_smaller">
				<ul> 
					<li> <strong> <%= link_to kid.first_name.capitalize, kid  %> </strong> </li>
					<li> <strong>School: </strong><%= kid.school.name  %> </li>
					<li> <strong>Suburb: </strong><%= kid.user.suburb  %></li>
				</ul>
				<% if @current_user.id == @trip.user_id || @current_user.id == kid.user_id || @current_user.admin %>
					<div class="btn btn-group-lg btn-warning btn-small" > 
						<%= link_to 'Remove Child', trip_unbook_path(@trip, kid), :method => :delete %> 
					</div>
				<% end %>
			</div>
		</div>
		<% end %>

	</div>

<!-- MESSAGING -->
	<div class="messaging">	
 	<% if @current_user  %> 
 	<h2>Messages </h2>

	    <% @trip.comments.each do |comment| %>
	    <div class="comment_block">
	        <div class="name_comment"> <h3> <%= link_to comment.user.first_name, user_path %></h3> </div>
	        <div class="comment_text"> 
	        <h4>	<%= comment.comment_text %></h4> 
	        <p> <%= comment.created_at.strftime "%I:%M %P, %B %d, %Y"  %> </p>
	        </div>

		    <div class="trip_comment_buttons">
				<% if @current_user.id == @trip.user_id || @current_user.id == comment.user_id || @current_user.admin %>
		<!-- Edit Button -->
					<!-- <div class="btn btn-group-lg btn-warning" > <%= link_to('Edit Comment', edit_trip_comment_path(@trip, comment)) %> </div> -->
		<!-- Delete Button -->
					<div class="btn btn-group-lg btn-danger" > <%= link_to 'Delete', trip_comment_path(@trip, comment), :method => :delete %> </div>

				<% end %>
			</div>
			</div>
		<% end %> 

	    <%= form_for ([@trip, @trip.comments.new]) do |f|  %>
		    <div class="input-group">
			  <%= f.text_area :comment_text , :autofocus => true, :placeholder => "Comment", :class =>  	"form-control" %>
		      <span class="input-group-btn">
		      		<%= f.submit "Post!", :class => "btn btn-default btn-lg"%>
  		      </span>
		    </div><!-- /input-group -->
	    <% end %>
    <% end %>
	</div>

<!-- MAP PART -->
    <section id="contact" class="map">
    <% if @trip.direction == 'dropoff' # Dropoff at school %>
	    <% @origin = @trip.user.map_address %>
	    <% @destination = @trip.school.map_address %>
    <% else %>
    	 <%@destination = @trip.user.map_address %>
	    <% @origin = @trip.school.map_address %>
    <% end %>

    <% if @trip.kids.length > 0 %>
	<iframe
	width="100%" height="100%" marginheight="0" marginwidth="0"
	  frameborder="0" style="border:0"
	  src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyByeW3PQr7VCnExkxH9pas6C2EfAUDdDsQ
	  &origin=<%= @origin.gsub(' ', '+').gsub(',', '+').gsub('++', '+')  %>&destination=<%= @destination.gsub(' ', '+').gsub(',', '+').gsub('++', '+')  %>&mode=driving&waypoints=<% @trip.kids.each_with_index do |kid, index| %><% if index != (@trip.kids.length - 1) %><%=kid.user.map_address%>|<% else %><%=kid.user.map_address%><%end%><%end%>"
	</iframe>
	<% else #if there is no new passengers %> 
	<iframe
	width="100%" height="100%" marginheight="0" marginwidth="0"
	  frameborder="0" style="border:0"
	  src="https://www.google.com/maps/embed/v1/directions?key=AIzaSyByeW3PQr7VCnExkxH9pas6C2EfAUDdDsQ
	  &origin=<%= @origin.gsub(' ', '+').gsub(',', '+').gsub('++', '+')  %>&destination=<%= @destination.gsub(' ', '+').gsub(',', '+').gsub('++', '+')  %>&mode=driving"
	</iframe>
	<% end %>
	</section> 

<% end %>
</div>