config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#        root GET    /                           home#index
#       about GET    /about(.:format)            home#about
#     contact GET    /contact(.:format)          home#contact
#   edit_user GET    /users/edit(.:format)       users#edit
#       users GET    /users(.:format)            users#index
#             POST   /users(.:format)            users#create
#    new_user GET    /users/new(.:format)        users#new
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
#        kids GET    /kids(.:format)             kids#index
#             POST   /kids(.:format)             kids#create
#     new_kid GET    /kids/new(.:format)         kids#new
#    edit_kid GET    /kids/:id/edit(.:format)    kids#edit
#         kid GET    /kids/:id(.:format)         kids#show
#             PATCH  /kids/:id(.:format)         kids#update
#             PUT    /kids/:id(.:format)         kids#update
#             DELETE /kids/:id(.:format)         kids#destroy
#     schools GET    /schools(.:format)          schools#index
#             POST   /schools(.:format)          schools#create
#  new_school GET    /schools/new(.:format)      schools#new
# edit_school GET    /schools/:id/edit(.:format) schools#edit
#      school GET    /schools/:id(.:format)      schools#show
#             PATCH  /schools/:id(.: format)      schools#update
#             PUT    /schools/:id(.:format)      schools#update
#             DELETE /schools/:id(.:format)      schools#destroy
#       trips GET    /trips(.:format)            trips#index
#             POST   /trips(.:format)            trips#create
#    new_trip GET    /trips/new(.:format)        trips#new
#   edit_trip GET    /trips/:id/edit(.:format)   trips#edit
#        trip GET    /trips/:id(.:format)        trips#show
#             PATCH  /trips/:id(.:format)        trips#update
#             PUT    /trips/:id(.:format)        trips#update
#             DELETE /trips/:id(.:format)        trips#destroy
#       login GET    /login(.:format)            session#new
#             POST   /login(.:format)            session#create
#             DELETE /login(.:format)            session#destroy
#

Rails.application.routes.draw do
  get 'messages/messages'

  get 'messages/index'

    root :to => 'home#index'
    get '/about' => 'home#about'
    get '/contact' => 'home#contact'

    get '/users/edit' => 'users#edit', :as => :edit_user
    resources :users, :except => [:edit]

    resources :kids, :schools
    resources :trips do
  	 resources :comments

     post 'book' => 'trips#book'  	
     delete 'unbook/:kid_id' => 'trips#unbook', :as => :unbook
    end


    get '/login' => 'session#new'
    post 'login' => 'session#create'
    delete 'login' => 'session#destroy'

end

app/models/kid.rb
# == Schema Information
#
# Table name: kids
#
#  id                  :integer          not null, primary key
#  first_name          :string(255)
#  last_name           :string(255)
#  dob                 :date
#  gender              :string(255)
#  image               :text             default("https://team.org/static/images/generic_avatar_300.gif")
#  description         :text
#  user_id             :integer
#  school_id           :integer
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class Kid < ActiveRecord::Base
	belongs_to :school
	belongs_to :user
	has_and_belongs_to_many :trips

### UPLOADING IMAGES
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/kids_controller.rb
class KidsController < ApplicationController

  # before_action :check_login

  def new
    @kid = Kid.new
  end

  def create
    kid = Kid.new kid_params
    kid.user_id = @current_user.id
    kid.save   
    redirect_to kid 
  end

  def index
    # List of schools user is part of
    @school_list = []
    @current_user.kids.each do |kid|
      @school_list << kid.school.id
    end  

    @kids = []
    @school_list.each do |school_id|
        Kid.all.each do |kid|
          if kid.school_id == school_id
            @kids << kid
          end
        end
      end
  end
  
  def show
    # Kids that belong to parents that are showed to you

    @kid = Kid.find params[:id]
    @result = Geocoder.search(@kid.user.map_address).first

  end

  def edit
    @kid = Kid.find params[:id]
  end

  def update
    kid = Kid.find params[:id]
    kid.update kid_params
    redirect_to kid
  end 

  def destroy
    kid = Kid.find params[:id]
    kid.delete
    redirect_to kids_path
  end

  private
  def kid_params
    params.require(:kid).permit(:avatar, :first_name, :last_name, :dob, :gender, :image, :description, :user_id, :school_id)
  end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_form.html.erb
	<div class="form_page">
		<div class="input-group">

	<%= form_for @kid do |f| %>
	<div class="form_segment">
		<%= f.label :first_name  , "First Name" %>
		<%= f.text_field :first_name , required: true, :class => "form-control" %>
	</div>
	<div class="form_segment">
		<%= f.label :last_name  , "Last Name" %>
		<%= f.text_field :last_name , required: true, :class => "form-control" %>
	</div>
	<div class="form_segment">
		<%= f.label :dob  , "Date of Birth" %>
		<%= f.date_field :dob , required: true, :class => "form-control"  %>
	</div>
	<div class="form_segment">
		<%= f.label :gender  , "Gender" %>
		<select name="kid[gender]", class="form-control",  required>
		  <option value="male">Male</option>
		  <option value="female">Female</option>
		</select>

	<div class="form_segment">
		<%= f.label :school, "School"  %>
		<select name="kid[school_id]", class="form-control", prompt="Select school", required>
			<option disabled>Select school</option>
			<% School.all.each do |school| %>
				<option value=<%= school.id %> > <%= school.name  %> </option>
			<% end %>
		</select>  
	</div>

<!-- 	<div class="form_segment">
		<%= f.label :image  , "Image" %>
		<%= f.url_field :image,  :class => "form-control"  %>
	</div>
 -->
<!-- Avatar -->
	<div class="form_segment">
	<div class="field">
  		<%= f.label :avatar %><br />
  		<%= f.file_field :avatar %>
	</div>
	</div>	
		<label></label>
		<%= f.submit %>
	<% end %>

	</div>
	</div>

app/views/kids/edit.html.erb
<div class="container">
<% if @current_user %>

<h1>Edit details of <%= @kid.first_name.capitalize  %></h1>

	<%= render :partial => 'form' %> 

<% end %>
</div>

app/views/kids/index.html.erb
<div class="container">
<h1>Kids in your area looking for help to go to school!</h1>
	<div class="btn btn-group-lg btn-success  btn-index"> 
		<%= link_to("New Kid", new_kid_path) %></div>
	<% @kids.each do |kid| %> 

		<div class="index">
		
      	<% if kid.avatar.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag kid.image %>
        <% else %>
             <%= image_tag kid.avatar.url %> 
        <% end %>

		</div>
		<div class="index"> <h3> <%= link_to kid.first_name.capitalize, kid  %> </h3>
		<h4> <strong>School: </strong><%= link_to kid.school.name, school_path(kid.school) %> </h4> 
		<h4> <strong>Age: </strong> <%= ((Date.today - kid.dob).to_f/365.25).round  %>-years-old </h4>
		<h4> <strong>Parent: </strong> <%= link_to kid.user.first_name.capitalize, user_path(kid.user)  %></h4>
		<h4><strong>Distance: </strong> <%= ((kid.user).distance_to([@current_user.user_latitude, @current_user.user_longitude])).round(2)   %> km away</h4>
		</div>

		<div class="index">

		<% @result = Geocoder.search(kid.user.map_address).first %>
		<iframe
			   width="285" height="285" marginheight="0" marginwidth="0" frameborder="0" style="border:0"

		  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyByeW3PQr7VCnExkxH9pas6C2EfAUDdDsQ
		    &q=<%= @result.latitude %>,<%= @result.longitude  %>">
		</iframe>

		</div>
	<% end %>

</div>

app/views/kids/new.html.erb
<div class="container">
<% if @current_user %>

	<h1>Add a new child!</h1>

	<%= render :partial => 'form' %> 

<% end %>
</div>

app/views/kids/show.html.erb
<div class="container">
<% if @current_user %>

<div class="show_column">
	<h1> <%= @kid.first_name.capitalize  %></h1>
	
      	<% if @kid.avatar.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag @kid.image %>
        <% else %>
             <%= image_tag @kid.avatar.url %> 
        <% end %>
	
	<h4> <strong>Gender: </strong><%= @kid.gender.capitalize  %> </h4>
	<h4> <strong>Age: </strong><%= ((Date.today - @kid.dob).to_f/365.25).round  %>-years-old </h4>
	<h4> <strong>School: </strong><% @school = (School.find @kid.school_id)  %> <%= link_to(@school.name, @school)  %></h4>
	<h4> <%= @kid.description  %> </h4>

<!-- Edit segment -->	
	<% if @current_user.id == @kid.user_id || @current_user.admin %>
		<div class="btn btn-group-lg btn-warning"> 
			<%= link_to 'Edit Student', edit_kid_path(@kid) %> 
		</div>
		<div class="btn btn-group-lg btn-danger"> 
			<%= link_to 'Delete Student', @kid, :method => :delete, :data => { :confirm => "Are you sure?" } if @current_user.id = @kid.user_id %> 
		</div>
	<% end %>
</div>

<div class="show_column">
	<% user = User.find @kid.user_id  %>
		<h2><%= link_to(user.first_name.capitalize, user_path) %></h2>

      	<% if user.avatar.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag user.image %>
        <% else %>
             <%= image_tag user.avatar.url %> 
        <% end %>
		
		<h4><strong>Suburb:</strong> <%= user.suburb %>, <%= user.postcode %></h4>
		<h4><strong>Distance:</strong> <%= (user.distance_to([@current_user.user_latitude, @current_user.user_longitude])).round(2)   %> km away</h4>

<!-- Contacts -->
	     <div class="col-lg-10 col-lg-offset-1 text-center">
	        <ul class="list-unstyled">
                <li><h4><i class="fa fa-phone fa-fw"></i> <%= number_to_phone(user.phone_number)  %></h4></li>
                <li><h4><i class="fa fa-envelope-o fa-fw"></i>  <a href=<%= user.email %>><%= user.email %></a></h4></li>
                <li> - </li>
            </ul>
            <ul class="list-inline">
                <li>
                    <a href=<%= user.facebook  %>><i class="fa fa-facebook fa-fw fa-2x"></i></a>
                </li>
                <li>
                    <a href=<%= user.twitter  %>><i class="fa fa-twitter fa-fw fa-2x"></i></a>
                </li>
            </ul>	        	
		</div>
	</div>

	<div class="show_column">
		<h2><%= link_to "Trips", trips_path %></h2>
		<% @kid.trips.each do |trip| %>
		<% if trip.date >= Date.today %>

		<div class="show_box">
			<ul>
			<li><%= link_to(trip.school.name, trip) %></li>
			<li> <strong> Date: </strong> <%= trip.date.strftime "%a, %B %d, %Y"  %> </li>

			<li> <strong> Time: </strong> <%= trip.desired_start_time.strftime "%l:%M %p"  %> </li>

			<li> <strong> Direction: </strong> <%= trip.direction.capitalize  %> </li>
			<li> <strong> School: </strong> <%= trip.school.name  %> </li>
			<li><strong>Seats Remaining: </strong> <%= trip.seats_remaining  %></li>
			</ul>
		</div>
		<% end %>
		<% end %>
	</div>

    <section id="contact" class="map">	
		<iframe
		  width="100%" height="500" marginheight="0" marginwidth="0" frameborder="0" style="border:0"
		  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyByeW3PQr7VCnExkxH9pas6C2EfAUDdDsQ
		    &q=<%= @result.latitude %>,<%= @result.longitude  %>">
		</iframe>
	</section>


<% end %>
</div>