config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#        root GET    /                           home#index
#       about GET    /about(.:format)            home#about
#     contact GET    /contact(.:format)          home#contact
#   edit_user GET    /users/edit(.:format)       users#edit
#       users GET    /users(.:format)            users#index
#             POST   /users(.:format)            users#create
#    new_user GET    /users/new(.:format)        users#new
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
#        kids GET    /kids(.:format)             kids#index
#             POST   /kids(.:format)             kids#create
#     new_kid GET    /kids/new(.:format)         kids#new
#    edit_kid GET    /kids/:id/edit(.:format)    kids#edit
#         kid GET    /kids/:id(.:format)         kids#show
#             PATCH  /kids/:id(.:format)         kids#update
#             PUT    /kids/:id(.:format)         kids#update
#             DELETE /kids/:id(.:format)         kids#destroy
#     schools GET    /schools(.:format)          schools#index
#             POST   /schools(.:format)          schools#create
#  new_school GET    /schools/new(.:format)      schools#new
# edit_school GET    /schools/:id/edit(.:format) schools#edit
#      school GET    /schools/:id(.:format)      schools#show
#             PATCH  /schools/:id(.: format)      schools#update
#             PUT    /schools/:id(.:format)      schools#update
#             DELETE /schools/:id(.:format)      schools#destroy
#       trips GET    /trips(.:format)            trips#index
#             POST   /trips(.:format)            trips#create
#    new_trip GET    /trips/new(.:format)        trips#new
#   edit_trip GET    /trips/:id/edit(.:format)   trips#edit
#        trip GET    /trips/:id(.:format)        trips#show
#             PATCH  /trips/:id(.:format)        trips#update
#             PUT    /trips/:id(.:format)        trips#update
#             DELETE /trips/:id(.:format)        trips#destroy
#       login GET    /login(.:format)            session#new
#             POST   /login(.:format)            session#create
#             DELETE /login(.:format)            session#destroy
#

Rails.application.routes.draw do
  get 'messages/messages'

  get 'messages/index'

    root :to => 'home#index'
    get '/about' => 'home#about'
    get '/contact' => 'home#contact'

    get '/users/edit' => 'users#edit', :as => :edit_user
    resources :users, :except => [:edit]

    resources :kids, :schools
    resources :trips do
  	 resources :comments

     post 'book' => 'trips#book'  	
     delete 'unbook/:kid_id' => 'trips#unbook', :as => :unbook
    end


    get '/login' => 'session#new'
    post 'login' => 'session#create'
    delete 'login' => 'session#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :integer          not null, primary key
#  username                :string(255)
#  first_name              :string(255)
#  last_name               :string(255)
#  email                   :string(255)
#  password_digest         :string(255)
#  facebook                :text
#  twitter                 :text
#  image                   :text             default("https://team.org/static/images/generic_avatar_300.gif")
#  phone_number            :string(255)
#  family_description      :text
#  car_brand               :string(255)
#  car_model               :string(255)
#  car_image               :string(255)      default("http://www.huntsgamepreserve.com/sitebuildercontent/sitebuilderpictures/webassets/car-icon.gif")
#  street_address          :text
#  suburb                  :string(255)
#  postcode                :integer
#  state                   :string(255)
#  map_address             :text
#  user_latitude           :float
#  user_longitude          :float
#  admin                   :boolean
#  created_at              :datetime
#  updated_at              :datetime
#  avatar_file_name        :string(255)
#  avatar_content_type     :string(255)
#  avatar_file_size        :integer
#  avatar_updated_at       :datetime
#  car_avatar_file_name    :string(255)
#  car_avatar_content_type :string(255)
#  car_avatar_file_size    :integer
#  car_avatar_updated_at   :datetime
#

class User < ActiveRecord::Base
	has_secure_password
	has_many :kids
	has_many :schools, through: :kids
	has_many :trips
	has_many :comments

	validates :username, :presence => true, :uniqueness => true, :length => {:minimum => 2, :maximum => 20}
	validate :email, :presence => true, :uniqueness => true

	geocoded_by :map_address, :latitude  => :user_latitude, :longitude => :user_longitude
	after_validation :geocode


### UPLOADING IMAGES
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar 

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

### UPLOADING IMAGES
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :car_avatar

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :car_avatar, :content_type => /\Aimage\/.*\Z/


end

app/controllers/users_controller.rb
# if Rails.env.development?
#   require 'openssl'
#   OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
# end

class UsersController < ApplicationController

  # before_action :check_login

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user.username.downcase!         # Ensuring the username is not case-sensitive
    @user.map_address = @user.street_address.to_s + ', ' + @user.suburb.to_s + ', ' + @user.postcode.to_s
    

    @result = Geocoder.search(@user.map_address).first
    @user.user_latitude = @result.latitude
    @user.user_latitude = @result.longitude

    if @user.save     # => true
      # here the user is valid
      session[:user_id] = @user.id
      redirect_to user_path(@user)   # back to the home page!
    else
      # here the user is invalid
      render :new         # reloads the page with everything they saved in @user already! :O
    end
  end

  def index
    # Users that have kids who go to your school
    @school_list = []
    @current_user.kids.each do |kid|
      @school_list << kid.school.id
    end
    @school_list.uniq!

    # Users that have kids who go to your school 
    @users = []
    @school_list.each do |school_id|
      User.all.each do |user|
        user.kids.each do |kid|
          if kid.school_id == school_id
            @users << user
          end
        end
      end
    end
  end  

  def show
    @user = User.find params[:id]
    @school_list = []
    @user.kids.each do |kid|
      school_name = kid.school.name
      @school_list << school_name
    end
    @result = Geocoder.search(@user.map_address).first

  end

  def edit
    @user = @current_user
  end

  def update
    user = @current_user
    # raise params.inspect

    user.update user_params
    user.map_address = user.street_address.to_s + ', ' + user.suburb.to_s + ', ' + user.postcode.to_s

    @result = Geocoder.search(user.map_address).first
    user.user_latitude = @result.latitude
    user.user_latitude = @result.longitude
    
    user.save

    redirect_to user
  end

  def destroy
    user = @current_user
    user.delete
    redirect_to root
  end

  private
  def user_params
    params.require(:user).permit(:username, :avatar, :car_avatar, :first_name, :last_name, :email, :facebook, :twitter, :image, :password, :password_confirmation, :image, :phone_number, :family_description, :street_address, :suburb, :postcode, :state, :car_brand, :car_model, :car_image, :map_address)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<ol>
		<%  @user.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
	</ol>
<% end %>

<div class="form_page">
	<div class="input-group">

	<%=  form_for @user do |f|  %>
	<div class="form_segment">
		<%= f.label :username %>
		<%= f.text_field :username, :autofocus => true, required: true, :class => "form-control" %>
	</div>
	<div class="form_segment">
		<%= f.label :first_name %>
		<%= f.text_field :first_name, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :last_name %>
		<%= f.text_field :last_name, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :email %>
		<%= f.email_field :email, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :password %>
		<%= f.password_field :password, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, required: true, :class => "form-control" %>
	</div>
<!-- Avatar -->
	<div class="form_segment">
	<div class="field">
  		<%= f.label :avatar %><br />
  		<%= f.file_field :avatar %>
	</div>
	</div>

	<div class="form_segment">
		<%= f.label :street_address %>
		<%= f.text_field :street_address, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :suburb %>
		<%= f.text_field :suburb, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :postcode %>
		<%= f.text_field :postcode, required: true, :class => "form-control" %>
	</div>
	<div class="form_segment">
		<%= f.label :state %>
		<%= f.text_field :state, required: true, :class => "form-control" %>
	</div>


	<div class="form_segment">
		<%= f.label :image %>
		<%= f.url_field :image, :class => "form-control" %>
	</div>
	<div class="form_segment">
		<%= f.label :phone_number %>
		<%= f.text_field :phone_number, :class => "form-control" %>
	</div>
	<div class="form_segment">
		<%= f.label :facebook %>
		<%= f.url_field :facebook, :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :twitter %>
		<%= f.url_field :twitter, :class => "form-control"%>
	</div>
	
	<div class="form_segment">
		<%= f.label :car_brand %>
		<%= f.text_field :car_brand, :class => "form-control" %>
	</div>
	
	<div class="form_segment">
		<%= f.label :car_model %>
		<%= f.text_field :car_model, :class => "form-control" %>
	</div>
<!-- 	<div class="form_segment">
		<%= f.label :car_image %>
		<%= f.url_field :car_image , :class => "form-control"%>
	</div> -->
	
<!-- Car Avatar -->
	<div class="form_segment">
	<div class="field">
  		<%= f.label :car_avatar %><br />
  		<%= f.file_field :car_avatar %>
	</div>
	</div>

	<div class="form_segment">
		<label> </label>
		<%= f.submit %>
	</div>
	<% end %>
</div>
</div>

app/views/users/edit.html.erb
<div class="container">
<% if @current_user %>

<h1>Edit your profile</h1>

<%= render :partial => 'form' %> 

<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<h1>Other parents in your area!</h1>

		<% @users.uniq.each do |user| %> 

			<div class="index">
 
      	<% if user.avatar.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag user.image %>
        <% else %>
             <%= image_tag user.avatar.url %> 
        <% end %>


			</div>

			<div class="index"> <h3> <%= link_to user.first_name.capitalize, user  %> </h3>
			<h4> <strong> Suburb:</strong> <%= user.suburb.capitalize %> </h4> 
				<% school_list = [] %>
				<% user.kids.each do |kid| %>
					<% school_name = kid.school.name %>
					<% school_list << school_name %>			
				<% end %>
			<h4> <strong>Schools:</strong> <%= school_list.uniq.join ", "  %> </h4>
			<h4><strong>Distance:</strong> <%= user.distance_to([@current_user.user_latitude, @current_user.user_longitude]).round(2)  %> km away</h4>
			</div>


			<div class="index">

			<% @result = Geocoder.search(user.map_address).first %>
			<iframe
			   width="285" height="285" marginheight="0" marginwidth="0" frameborder="0" style="border:0"
			  frameborder="0" style="border:0"
			  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyByeW3PQr7VCnExkxH9pas6C2EfAUDdDsQ
			    &q=<%= @result.latitude %>,<%= @result.longitude  %>">
			</iframe>

			</div>	

	<% end %>

</div>

app/views/users/new.html.erb
<div class="container">

	<h1>Sign up for Little Wheels!</h1>

<% if @user.errors.any? %>
	<ol>
		<%  @user.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
	</ol>
<% end %>

<div class="form_page">
	<div class="input-group">

	<%=  form_for @user do |f|  %>
	<div class="form_segment">
		<%= f.label :username %>
		<%= f.text_field :username, :autofocus => true, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :first_name %>
		<%= f.text_field :first_name, required: true, :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :last_name %>
		<%= f.text_field :last_name, required: true, :class => "form-control"%>
	</div>
<!-- Avatar -->
	<div class="field">
  		<%= f.label :avatar %><br />
  		<%= f.file_field :avatar %>
	</div>
	<div class="form_segment">
		<%= f.label :email %>
		<%= f.email_field :email, required: true, :class => "form-control" %>
	</div>
	<div class="form_segment">
		<%= f.label :password %>
		<%= f.password_field :password, required: true, :class => "form-control" %>
	</div>
	<div class="form_segment">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :street_address %>
		<%= f.text_field :street_address, required: true, :class => "form-control" %>
	</div>
	<div class="form_segment">
		<%= f.label :suburb %>
		<%= f.text_field :suburb, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :postcode %>
		<%= f.text_field :postcode, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<%= f.label :state %>
		<%= f.text_field :state, required: true , :class => "form-control"%>
	</div>
	<div class="form_segment">
		<label> </label>
		<%= f.submit %>
	</div>
	<% end %>
	</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<% if @current_user %>

	<div class="show_column">

		<h2><strong><%= @user.first_name.capitalize  %> <%= @user.last_name.capitalize  %></strong></h2>


        <% if @user.avatar.url.split(//).last(11).join == "missing.png"  %>
            <%= image_tag @user.image %>
        <% else %>
             <%= image_tag @user.avatar.url %> 
        <% end %>


		<h4><strong>Schools: </strong> <%=  @school_list.uniq.join ", " %></h4>
		<h4><strong>Distance: </strong> <%= (@user.distance_to([@current_user.user_latitude, @current_user.user_longitude])).round(2)   %> km away</h4>
		<h4> <strong>Vehicle: </strong> <%= @user.car_brand  %> <%= @user.car_model %> </h4>

      	<% if @user.car_avatar.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag @user.car_image %>
        <% else %>
             <%= image_tag @user.car_avatar.url %> 
        <% end %>

<!-- Contacts -->
	     <div class="col-lg-10 col-lg-offset-1 text-center">
	        <ul class="list-unstyled">
                <li><i class="fa fa-phone fa-fw"></i> <%= number_to_phone(@user.phone_number)  %></li>
                <li><i class="fa fa-envelope-o fa-fw"></i>  <a href=<%= @user.email %>><%= @user.email %></a>
                </li>
                <li> - </li>
            </ul>
            <ul class="list-inline">
                <li>
                    <a href=<%= @user.facebook  %>><i class="fa fa-facebook fa-fw fa-2x"></i></a>
                </li>
                <li>
                    <a href=<%= @user.twitter  %>><i class="fa fa-twitter fa-fw fa-2x"></i></a>
                </li>
            </ul>	        	
		</div>
	<div>
		<% if @current_user.admin || @current_user.id = @user.id%>
			<div class="btn btn-group-lg btn-warning"> 
			<%= link_to("Edit Profile", edit_user_path(@user)) %></div>
		<% end %>
		<% if @current_user.admin %>
		<div class="btn btn-group-lg btn-danger"> 
		<%= link_to 'Delete Profile', @user, :method => :delete, :data => { :confirm => "Are you sure?" } %>
		</div>
		<% end %>
	</div>
	</div>

	<div class="show_column">
		<h2><%=  link_to "Children", kids_path %></h2>
		<% @user.kids.each do |kid| %>
		<div class="show_box">
			<div class="show_box_smaller">

      	<% if kid.avatar.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag kid.image %>
        <% else %>
             <%= image_tag kid.avatar.url %> 
        <% end %>		

			</div>

			<div class="show_box_smaller">
				<ul> 
					<li> <%= link_to kid.first_name.capitalize, kid  %> </li>
					<li> <%= kid.school.name  %> </li>
					<li><%= ((Date.today - kid.dob).to_f/365.25).round  %>-years-old </li>
				</ul>
			</div>
		</div>
		<% end %>
	<% if @current_user.id == @user.id || @current_user.admin %>	
	<div class="btn btn-group-lg btn-success"> 
		<%= link_to("Add Kid", new_kid_path) %></div>
	<% end %>

	
	</div>

	<div class="show_column">
		<h2><%= link_to "Trips", trips_path %></h2>
		<% @user.trips.each do |trip| %>
		<% if trip.date >= Date.today %>
		<div class="show_box">
			<ul>
			<li><%= link_to(trip.school.name, trip) %></li>
			<li> <strong> Date: </strong> <%= trip.date.strftime "%a, %B %d, %Y"  %> </li>

			<li> <strong> Time: </strong> <%= trip.desired_start_time.strftime "%l:%M %p"  %> </li>

			<li> <strong> Direction: </strong> <%= trip.direction.capitalize  %> </li>
			<li> <strong> School: </strong> <%= trip.school.name  %> </li>
			<li><strong>Seats Remaining: </strong> <%= trip.seats_remaining  %></li>
			</ul>
		</div>
		<% end %>
		<% end %>

	<% if @current_user.id == @user.id || @current_user.admin %>	
		<div class="btn btn-group-lg btn-success"> 
			<%= link_to("Add Trip", new_trip_path) %>
		</div>
	<% end %>

	</div>

    <section id="contact" class="map">	
		<iframe
		  width="100%" height="500" marginheight="0" marginwidth="0" frameborder="0" style="border:0"
		  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyByeW3PQr7VCnExkxH9pas6C2EfAUDdDsQ
		    &q=<%= @user.user_latitude %>,<%= @user.user_longitude  %>">
		</iframe>
	</section>

<% end %>
</div>