config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#        root GET    /                           home#index
#       about GET    /about(.:format)            home#about
#     contact GET    /contact(.:format)          home#contact
#   edit_user GET    /users/edit(.:format)       users#edit
#       users GET    /users(.:format)            users#index
#             POST   /users(.:format)            users#create
#    new_user GET    /users/new(.:format)        users#new
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
#        kids GET    /kids(.:format)             kids#index
#             POST   /kids(.:format)             kids#create
#     new_kid GET    /kids/new(.:format)         kids#new
#    edit_kid GET    /kids/:id/edit(.:format)    kids#edit
#         kid GET    /kids/:id(.:format)         kids#show
#             PATCH  /kids/:id(.:format)         kids#update
#             PUT    /kids/:id(.:format)         kids#update
#             DELETE /kids/:id(.:format)         kids#destroy
#     schools GET    /schools(.:format)          schools#index
#             POST   /schools(.:format)          schools#create
#  new_school GET    /schools/new(.:format)      schools#new
# edit_school GET    /schools/:id/edit(.:format) schools#edit
#      school GET    /schools/:id(.:format)      schools#show
#             PATCH  /schools/:id(.: format)      schools#update
#             PUT    /schools/:id(.:format)      schools#update
#             DELETE /schools/:id(.:format)      schools#destroy
#       trips GET    /trips(.:format)            trips#index
#             POST   /trips(.:format)            trips#create
#    new_trip GET    /trips/new(.:format)        trips#new
#   edit_trip GET    /trips/:id/edit(.:format)   trips#edit
#        trip GET    /trips/:id(.:format)        trips#show
#             PATCH  /trips/:id(.:format)        trips#update
#             PUT    /trips/:id(.:format)        trips#update
#             DELETE /trips/:id(.:format)        trips#destroy
#       login GET    /login(.:format)            session#new
#             POST   /login(.:format)            session#create
#             DELETE /login(.:format)            session#destroy
#

Rails.application.routes.draw do
  get 'messages/messages'

  get 'messages/index'

    root :to => 'home#index'
    get '/about' => 'home#about'
    get '/contact' => 'home#contact'

    get '/users/edit' => 'users#edit', :as => :edit_user
    resources :users, :except => [:edit]

    resources :kids, :schools
    resources :trips do
  	 resources :comments

     post 'book' => 'trips#book'  	
     delete 'unbook/:kid_id' => 'trips#unbook', :as => :unbook
    end


    get '/login' => 'session#new'
    post 'login' => 'session#create'
    delete 'login' => 'session#destroy'

end

app/models/school.rb
# == Schema Information
#
# Table name: schools
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  website           :text
#  phone             :string(255)
#  image             :text             default("http://cdns2.freepik.com/free-photo/school_318-23393.jpg")
#  street_address    :text
#  suburb            :string(255)
#  postcode          :integer
#  state             :string(255)
#  map_address       :text
#  school_latitude   :float
#  school_longitude  :float
#  start_time        :time
#  finish_time       :time
#  logo_file_name    :string(255)
#  logo_content_type :string(255)
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#

class School < ActiveRecord::Base
	has_many :trips
	has_many :kids
	has_many :users, through: :kids

	geocoded_by :map_address, :latitude  => :school_latitude, :longitude => :school_longitude
	after_validation :geocode

### UPLOADING IMAGES
  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :logo

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  # before_action :check_login

  def new
    @school = School.new
  end

  def create
  @school = School.new school_params
  @school.map_address = @school.name.to_s + ', ' + @school.street_address.to_s + ', ' + @school.suburb.to_s + ', ' + @school.postcode.to_s
  @school.save   
  redirect_to schools_path
  end

  def index
    @schools = School.all
  end
  
  def show
    @school = School.find params[:id]
  end

  def edit
    @school = School.find params[:id]
  end

  def update
    school = School.find params[:id]
    school.update school_params
    school.map_address = school.name.to_s + ', ' + school.street_address.to_s + ', ' + school.suburb.to_s + ', ' + school.postcode.to_s
    school.save
    redirect_to school
  end 

  def destroy
    school = school.find params[:id]
    school.delete
    redirect_to schools
  end

  private
  def school_params
    params.require(:school).permit(:name, :image, :logo, :street_address, :suburb, :postcode, :state, :start_time, :finish_time, :map_address)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<div class="form_page">
	<div class="input-group">

	<%= form_for @school do |f| %>
	<div class="form_segment">
		<%= f.label :name  , "Name" %>
		<%= f.text_field :name, :class => "form-control"  , required: true%>
	</div>
<!-- 	<div class="form_segment">
		<%= f.label :image  , "School logo" %>
		<%= f.url_field :image , :class => "form-control" %>
	</div> -->
<!-- Logo -->
	<div class="form_segment">
	<div class="field">
  		<%= f.label :logo %><br />
  		<%= f.file_field :logo %>
	</div>
	</div>	
	<div class="form_segment">
		<%= f.label :street_address  , "Street address" %>
		<%= f.text_field :street_address , :class => "form-control" , required: true%>
	</div>
	<div class="form_segment">
		<%= f.label :suburb  , "Suburb" %>
		<%= f.text_field :suburb , :class => "form-control" , required: true%>
	</div>
	<div class="form_segment">
		<%= f.label :postcode  , "Post code" %>
		<%= f.text_field :postcode , :class => "form-control" , required: true%>
	</div>
	<div class="form_segment">
		<%= f.label :state  , "State" %>
		<%= f.text_field :state , :class => "form-control" , required: true%>
	</div>
	<div class="form_segment">
		<%= f.label :state_time  , "Start time" %>
		<%= f.time_field :start_time , :class => "form-control" , required: true%>
	</div>
	<div class="form_segment">
		<%= f.label :finish_time  , "Finish time" %>
		<%= f.time_field :finish_time , :class => "form-control" , required: true%>
	</div>
		<label></label>
		<%= f.submit %>
	<% end %>
</div>
</div>

app/views/schools/edit.html.erb
<div class="container">
<% if @current_user %>

	<h1>Edit school details</h1>
	<%= render :partial => 'form' %> 

<% end %>
</div>

app/views/schools/index.html.erb
<div class="container">
	<h1>Schools in your area</h1>
	<div class="btn btn-group-lg btn-success btn-index"> 
		<%= link_to("New School", new_school_path) %></div>

	<% @schools.each do |school| %> 
			<div class="index">	

      	<% if school.logo.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag school.image %>
        <% else %>
             <%= image_tag school.logo.url %> 
        <% end %>	
						
			</div>

			<div class="index">
				<h3> <%= link_to school.name, school  %> </h3>
				<h4><strong>Address: </strong><%= school.street_address  %></h4>
				<h4><strong>Suburb: </strong><%= school.suburb %>, <%= school.postcode  %>, <%= school.state  %></h4>
				<h4><strong>Hours: </strong><%= school.start_time.strftime "%I:%M %p"   %> - <%= school.finish_time.strftime "%I:%M %p"   %></h4>
				<h4><strong>Distance:</strong> <%= school.distance_to([@current_user.user_latitude, @current_user.user_longitude]).round(2)  %> km away</h4>
				<h4><strong>Students:</strong> <%= school.kids.count  %> students</h4>
				<h4><strong>Active Trips:</strong> 
					<% active_trips = [] %>
					<% school.trips.each do |trip|   %>
						<% if trip.date >= Date.today  %>
							<% active_trips << trip %>
						<% end %>
					<% end %>
				<%= active_trips.count  %> available </h4>
			</div>

			<div class="index">
				<iframe
			   width="285" height="285" marginheight="0" marginwidth="0" frameborder="0" style="border:0"

				  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyByeW3PQr7VCnExkxH9pas6C2EfAUDdDsQ
				    &q=<%= school.map_address  %>">
				</iframe>
			</div>
	<% end %>
	</ul>

</div>

app/views/schools/new.html.erb
<div class="container">
<% if @current_user %>

	<h1>Add a new school</h1>
	<%= render :partial => 'form' %> 

<% end %>
</div>

app/views/schools/show.html.erb
<div class="container">
<% if @current_user %>

	<div class="show_column">

		<h2>
			<%= @school.name  %>
		</h2>
      	<% if @school.logo.url.chars.last(11).join == "missing.png"  %>
            <%= image_tag @school.image %>
        <% else %>
             <%= image_tag @school.logo.url %> 
        <% end %>		

		<h4>
			<strong>Address:</strong> <%= @school.street_address  %>
		</h4>
		<h4>
			<strong>Suburb:</strong> <%= @school.suburb  %>, <%= @school.postcode  %>
		</h4>
		<h4>
			<strong>State:</strong> <%= @school.state  %>
		</h4>
		<h4>
			<strong>Start Time:</strong> <%= @school.start_time.strftime "%I:%M %p"  %>
		</h4>
		<h4>
			<strong>Finish Time:</strong> <%= @school.finish_time.strftime "%I:%M %p"  %> 
		</h4>
		<h4><strong>Distance:</strong> <%= @school.distance_to([@current_user.user_latitude, @current_user.user_longitude]).round(2)  %> km away</h4>

		<div class="btn btn-group-lg btn-warning"> 
			<%= link_to('Edit School', edit_school_path(@school))   %>
		</div>
		<div class="btn btn-group-lg btn-danger"> 
			<%= link_to 'Delete', @school, :method => :delete, :data => { :confirm => "Are you sure?" } %>
		</div>
	</div>

	<div class="show_column">
	<h2><%= link_to "Trips", trips_path %> 
	<!-- # Active trips -->
	<% active_trips = [] %>
	<% @school.trips.each do |trip| %>
		<% if trip.date >= Date.today %>
			<% active_trips << trip %>
		<% end %>
	<% end %>
	(<%= active_trips.count  %>)</h2>
		<% @school.trips.each do |trip|  %>
		<% if trip.date > Date.today %>
		<div class="show_box">
			<ul>

			<li><strong>Driver: </strong><%= link_to(trip.user.first_name.capitalize, user_path(trip.user)) %>, <%= trip.user.suburb  %></li>
			<li> <strong> Date: </strong> <%= trip.date.strftime "%a, %B %d, %Y"  %> </li>

			<li> <strong> Time: </strong> <%= trip.desired_start_time.strftime "%l:%M %p"  %> </li>

			<li> <strong> Direction: </strong> <%= trip.direction.capitalize  %> </li>
			<li><strong>Seats Remaining: </strong> <%= trip.seats_remaining  %></li>
			</ul>
		</div>
		<% end %>
		<% end %>
	</div>


	<div class="show_column">
	<h2><%= link_to "Students", kids_path %> (<%= @school.kids.count  %>)</h2>
	<% @school.kids.each do |kid|  %>
		<div class="show_box">
			<div class="show_box_smaller">

		      	<% if kid.avatar.url.chars.last(11).join == "missing.png"  %>
		            <%= image_tag kid.image %>
		        <% else %>
		             <%= image_tag kid.avatar.url %> 
		        <% end %>		
		        		
			</div>
			<div class="show_box_smaller">
				<ul>
				<li><%= link_to kid.first_name.capitalize, kid  %></li>
				<li><%= ((Date.today - kid.dob).to_f/365.25).round  %>-years-old</li>
				<li><%= kid.user.suburb  %></li>
				<li><strong>Parent: </strong><%= link_to kid.user.first_name.capitalize, user_path  %></li>
				</ul>
			</div>
		</div>
	<% end %>
	</div>

    <section id="contact" class="map">
		<iframe
		  width="100%" height="500" marginheight="0" marginwidth="0" frameborder="0" style="border:0"
		  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyByeW3PQr7VCnExkxH9pas6C2EfAUDdDsQ
		    &q=<%= @school.map_address  %>">
		</iframe>
	</section>

<% end %>
</div>